### ISSUE TITLE
Wrong IP

### ISSUE THREAD

**Issue by Lavrentij** [tdanielcox/bluesnap-php#2]
Sorry my english...
When you test your application from wrong IP (not IP that bound for BlueSnap)
then in Utility.php on 19 - "if (is_array($errors->message))":
ErrorException (E_NOTICE)
Undefined property: stdClass::$message
That is not mistake sure, but if you fix it - your pack will be better )

**Comment by tdanielcox** [comment]
thank you for letting me know, I will look into fixing this when I have some time
