### ISSUE TITLE
Hello again

### ISSUE THREAD

**Issue by Lavrentij** [tdanielcox/bluesnap-php#4]
class Adapter
$message = $e->getResponse()->getBody()->getContents();
            $message = Utility::parseBluesnapErrors($message);
            return new Response('error', $message);

For what you did so? Deleted all info except message text. Sorry, but its very bad idea.

For example - How doing localization now - full message key?

**Comment by tdanielcox** [comment]
Hello, unfortunately I have discontinued development of this project quite some time ago. I leave it up as a starting point for anyone who wants to use it and modify it to fit their needs. Please feel free to fork it and continue development.
